Search/Alerts/Auth
chayan007/rozprava-frontend pull request #15
Opened 2021-06-19 13:03 UTC by itisdb

- Search bar has been implemented in the front end
- the is_authenticated() function has been used in App.vue
- alerts integration has been done.

If you find any disarray in the code or a snippet that you don't understand please let me know.

2021-06-19 14:16 UTC, chayan007 requested changes

2021-06-19 14:16 UTC, chayan007 commented on src/App.vue
> +    },
erase trailing `,` if not required

2021-06-19 14:16 UTC, chayan007 commented on src/components/NavReg.vue
> +          <!-- this is just a dev component this will be removed-->
Please give proper name to components. `NavRegistration` or `NavAuthMenu`

2021-06-19 14:16 UTC, chayan007 commented on src/App.vue
> +    <Alert />
How are you getting the message in the component ? Props from this component has not been passed onto this child component `Alert`.

2021-06-19 14:16 UTC, chayan007 commented on src/router/index.js
> +      const x=1; // emulating the value of the condition check for the sign in.
Please remove component switching logic based on authentication from routes to the view.

2021-06-19 14:16 UTC, chayan007 commented on src/views/search.vue
> +
Please check these lints of trailing spaces and `,`

2021-06-19 14:16 UTC, chayan007 commented on src/views/search.vue
> +import SearchBar from '../components/search/searchBar.vue'
use `@` notation

2021-06-19 14:16 UTC, chayan007 commented on src/router/index.js
> +import Splash from '../views/Splash.vue'
use `@` notation for all.

2021-06-19 14:16 UTC, chayan007 commented on src/components/search/searchBar.vue
> +            "
Please see these lint issues.

2021-06-19 14:16 UTC, chayan007 commented on src/components/search/searchBar.vue
> +//import { defineComponent } from '@vue/composition-api'
If not required, remove completely.

2021-06-19 14:16 UTC, chayan007 commented on src/components/alerts/alert.vue
> +export default {
Can you please attach screenshots of this component ?

2021-06-19 14:16 UTC, chayan007 commented on src/components/NavReg.vue
> +                >
Please check lints for this entire file properly.

2021-06-19 14:17 UTC, itisdb commented on src/App.vue
> +    },
ok working on it

2021-06-23 20:02 UTC, chayan007 commented on src/components/Navigation.vue
> +                >
@itisdb please try to check this kind of issues. Maybe you are using some kind of prettier formatter which is creating such messy code.

WRONG:
```
...</a
>
```

CORRECT:
```
...
</a>
```

2021-06-23 20:04 UTC, chayan007 commented on src/components/SettingsPage.vue
>    components: { AdSettings },
Please rename this to `AdvancedSettings`, there will be an `AdSettings` component in future.

2021-06-23 20:05 UTC, chayan007 commented on src/components/search/searchBar.vue
> +            "
@itisdb please check this lint issues. One line is used just for `"`

2021-06-23 20:05 UTC, chayan007 commented on src/views/search.vue
> +import SearchBar from '../components/search/searchBar.vue'
@itisdb

2021-06-23 20:06 UTC, chayan007 commented on src/components/Navigation.vue
> +
Please check, there are lot of wasted newlines.

2021-06-24 07:11 UTC, chayan007 commented on src/components/Navigation.vue
> +                >
@itisdb unaddressed

2021-06-24 07:11 UTC, chayan007 approved these changes

2021-06-24 07:13 UTC, vikas339 approved these changes

2021-06-24 07:14 UTC, merged