Profile Page
chayan007/rozprava-frontend pull request #19
Opened 2021-07-08 12:37 UTC by raju-max

2021-07-10 08:52 UTC, chayan007 commented on src/components/AdvancedSettings.vue
> +                        <option selected="">Choose...</option>
Please use -> `data/country.json`, which will have the following:

```
{
"IN": "India",
"US": "United States of America",
"CA": "Canada",
...
}
```

2021-07-10 08:52 UTC, chayan007 commented on src/components/CategoryForm.vue
> +                <!--End of Buttons-->
remove unnecessary comments.

2021-07-10 08:53 UTC, chayan007 commented on src/components/PostButton.vue
> +            <img src="../assets/Edit.png" alt="sign in" width="30">
`alt` to be changed for all of the buttons.

2021-07-10 08:54 UTC, chayan007 commented on src/services/user.service.js
> +/*function edit_settings(settings_data){
remove if not required.

2021-07-10 08:54 UTC, chayan007 commented on src/components/ProfileMenu.vue
> +
please remove spaces.

2021-07-10 08:54 UTC, chayan007 commented on src/components/SettingsPage.vue
> +              >Change <a style="color: green">Profile Password</a></span
reason for adding a space ?

2021-07-10 08:54 UTC, chayan007 commented on src/configurations/user.js
> +            },
delete if not required.

2021-07-10 08:55 UTC, chayan007 requested changes

2021-07-10 08:55 UTC, chayan007 commented on src/components/LoginForm.vue
> +
Why are you removing these values ? This will stop the login flow ?

2021-07-26 07:37 UTC, itisdb approved these changes

2021-07-26 16:26 UTC, chayan007 approved these changes

2021-07-26 16:28 UTC, chayan007 requested changes

2021-07-26 16:28 UTC, chayan007 commented on src/views/Category.vue
> +  components: { CategoryForm ,PeopleCard
please check this kind of irregularities.

2021-07-26 16:28 UTC, chayan007 commented on src/views/Post.vue
> +  components: { Post1,PostButton,PostButton2 },
give one space after `,`

2021-07-26 16:28 UTC, chayan007 commented on src/views/SingleChatPage.vue
> +  components: { SingleChat, },
why is there a trailing `,` for no reason ?

2021-08-08 04:26 UTC, closed without merging