Case view
chayan007/rozprava-frontend pull request #20
Opened 2021-07-12 07:21 UTC by ayushi-siddhu

2021-07-15 12:59 UTC, chayan007 requested changes
1. CaseViewPage to be pulled inside the CaseView. Hence, CaseViewPage (which is a component) needs to be deleted.
2. Page Design has serious flaws. Please coordinate with @itisdb (one of them - I can see the navbar and page elements merged together.)

2021-07-15 12:59 UTC, chayan007 commented on src/router/index.js
> +     component: CaseView
Did you import `CaseView`? This should throw error for sure.

2021-07-15 12:59 UTC, chayan007 commented on src/views/CaseView.vue
> +// @ is an alias to /src
remove comment !

2021-07-15 12:59 UTC, chayan007 commented on src/views/CaseView.vue
> +import CaseViewPage from '../components/CaseViewPage.vue';
a line gap please.

2021-07-15 12:59 UTC, chayan007 commented on src/views/CaseView.vue
> +import CaseViewPage from '../components/CaseViewPage.vue';
also use `@` instead of `..`

2021-07-15 13:03 UTC, raju-max approved these changes

2021-07-15 13:15 UTC, ayushi-siddhu commented on src/views/CaseView.vue
> +// @ is an alias to /src
done

2021-07-15 13:16 UTC, ayushi-siddhu commented on src/views/CaseView.vue
> +import CaseViewPage from '../components/CaseViewPage.vue';
ok

2021-07-15 17:51 UTC, raju-max approved these changes

2021-07-16 06:54 UTC, chayan007 approved these changes

2021-07-16 15:03 UTC, merged